name: 米游社签到

env:
  config: ${{ secrets.CONFIG }}

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  Run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 安装环境
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 获取代码
      run: |
        git clone https://github.com/Womsxd/AutoMihoyoBBS --depth=1

    - name: 安装依赖
      run: |
        cd AutoMihoyoBBS
        pip install -r requirements.txt

    - name: 配置参数
      run: |
        cd AutoMihoyoBBS
        echo $config > config/config.json
        
    - name: 执行签到
      run: |
        cd AutoMihoyoBBS
        python main.py
